# Generated by Django 3.0 on 2020-05-16 15:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OldRecord',
            fields=[
                ('oid', models.AutoField(primary_key=True, serialize=False)),
                ('ttype', models.CharField(max_length=2)),
                ('pickup_datetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='上车时间')),
                ('dropoff_datetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='上车时间')),
                ('passenger_count', models.IntegerField()),
                ('uplat', models.FloatField()),
                ('uplon', models.FloatField()),
                ('droplat', models.FloatField()),
                ('droplon', models.FloatField()),
                ('payment_type', models.IntegerField()),
                ('trip_distance', models.FloatField()),
                ('fare_amount', models.FloatField()),
                ('extra', models.FloatField()),
                ('total_amount', models.FloatField()),
            ],
            options={
                'db_table': 'old_nyc_taxi',
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('oid', models.AutoField(primary_key=True, serialize=False)),
                ('ttype', models.CharField(max_length=2)),
                ('pickup_datetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='上车时间')),
                ('dropoff_datetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='上车时间')),
                ('passenger_count', models.IntegerField()),
                ('PULocationID', models.IntegerField()),
                ('DOLocationID', models.IntegerField()),
                ('payment_type', models.IntegerField()),
                ('trip_distance', models.FloatField()),
                ('fare_amount', models.FloatField()),
                ('extra', models.FloatField()),
                ('total_amount', models.FloatField()),
            ],
            options={
                'db_table': 'nyc_taxi',
            },
        ),
    ]
